# Asterisk — the house PBX. Plain Asterisk on pjsip, no FreePBX: the whole
# dialplan is this file, so a phone-system change is a PR like everything else.
#
#   Dial 0        -> the switchboard (services/switchboard.nix): talk to the box.
#   Dial 9        -> voice audition: every piper voice says the same lines;
#                    any key = next, * = again, # = hang up.
#   Dial 1XX      -> ring that extension.
#   Dial 911      -> "no service" tone + hangup. THERE IS NO PSTN TRUNK. This
#                    PBX cannot reach emergency services; a real phone must.
#                    Revisit before any handset lives where someone might grab
#                    it in a hurry (E911 on a DID, or a route to a real line).
#
# Endpoints are declared here (extensions + labels); their passwords are NOT.
# An ExecStartPre generates /var/lib/asterisk/pjsip-auth.conf on first start —
# one random secret per extension, never rewritten — and pjsip.conf #includes
# it. Same pattern as homelab-mcp's credentials: nothing secret in git, and
#     sudo cat /var/lib/asterisk/pjsip-auth.conf
# is how you read the secret to type into a phone or ATA. Extensions ADDED to
# the list later get generated on the next start; removed ones are left in the
# file (harmless: no endpoint references them) — delete by hand if you care.
#
# Reachability: LAN + Tailscale only, like everything else on this box. SIP
# signalling on 5060/udp, RTP on a small pinned range. Nothing on the WAN.
{ config, lib, pkgs, ... }:

let
  cfg = config.services.homelab-pbx;

  # "101" -> pjsip endpoint + aor + (in the generated file) auth sections.
  endpointConf = ext: label: ''
    ; ${label}
    [${ext}](phone)
    auth=auth${ext}
    aors=${ext}
    callerid="${label}" <${ext}>

    [${ext}](phone-aor)
  '';

  authFile = "/var/lib/asterisk/pjsip-auth.conf";

  # Generates the auth sections and fixes the spool mode. Extensions arrive as
  # ARGV, not an env var —
  # a space-separated list in Environment= gets truncated to its first entry
  # and the unit still exits 0 (the content-archives bug, 3 weeks unnoticed).
  genAuth = pkgs.writeShellScript "asterisk-gen-auth" ''
    set -euo pipefail
    f=${authFile}
    umask 077
    [ -e "$f" ] || printf '; generated by asterisk-gen-auth — one secret per extension, never rewritten\n' > "$f"
    for ext in "$@"; do
      if ! grep -q "^\[auth$ext\]" "$f"; then
        pw="$(${pkgs.openssl}/bin/openssl rand -base64 18 | tr -d '/+=' | cut -c1-20)"
        printf '\n[auth%s](phone-auth)\nusername=%s\npassword=%s\n' "$ext" "$ext" "$pw" >> "$f"
        echo "asterisk-gen-auth: generated secret for extension $ext"
      fi
    done
    chown asterisk:asterisk "$f"
    chmod 0600 "$f"
    # The call-file spool: group-writable so the switchboard unit (in group
    # asterisk) can originate calls. The package skeleton does NOT ship
    # outgoing/ (Asterisk makes it on its first run), so create it here —
    # a bare chmod failed the very first start on 2026-09-11.
    install -d -m 2775 -o asterisk -g asterisk /var/spool/asterisk/outgoing
  '';
in
{
  options.services.homelab-pbx = {
    enable = lib.mkEnableOption "the house Asterisk PBX";

    localNet = lib.mkOption {
      type = lib.types.str;
      default = "192.168.1.0/24";
      description = "LAN subnet, so pjsip knows which peers are NOT behind NAT.";
    };

    extensions = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = {
        "101" = "Desk";
        "102" = "Kitchen";
        "103" = "Shop";
        "104" = "ATA port 1";
        "105" = "ATA port 2";
      };
      description = "Extension number -> caller-ID label. Secrets are generated at first start.";
    };

    rtpRange = lib.mkOption {
      type = lib.types.attrs;
      default = { from = 10000; to = 10199; };
      description = "UDP range for RTP media. 200 ports = ~100 concurrent calls, plenty.";
    };
  };

  config = lib.mkIf cfg.enable {
    services.asterisk = {
      enable = true;
      confFiles = {
        "pjsip.conf" = ''
          [transport-udp]
          type=transport
          protocol=udp
          bind=0.0.0.0:5060
          local_net=${cfg.localNet}
          local_net=100.64.0.0/10   ; tailscale — no NAT between tailnet peers

          ; --- templates ------------------------------------------------
          [phone](!)
          type=endpoint
          context=phones
          disallow=all
          allow=g722      ; wideband first if the phone offers it (piper output is 8 kHz for now)
          allow=ulaw
          allow=alaw
          direct_media=no
          rtp_symmetric=yes
          force_rport=yes
          rewrite_contact=yes
          dtmf_mode=auto_info   ; RFC 4733 when negotiated, SIP INFO otherwise (Linphone does either)
          language=en

          [phone-aor](!)
          type=aor
          max_contacts=2
          remove_existing=yes
          qualify_frequency=60

          [phone-auth](!)
          type=auth
          auth_type=userpass

          ; --- endpoints (labels here, secrets in the included file) -----
          ${lib.concatStringsSep "\n" (lib.mapAttrsToList endpointConf cfg.extensions)}

          #include ${authFile}
        '';

        "extensions.conf" = ''
          [general]
          static=yes
          writeprotect=yes

          [phones]
          ; 0 — the switchboard. Answer, hand the call to the FastAGI server.
          exten => 0,1,Goto(switchboard,s,1)

          ; 9 — audition the piper voices (samples are rendered at build time).
          exten => 9,1,Goto(voices,s,1)

          ; 1XX — ring an extension; voicemail is a later problem.
          exten => _1XX,1,Dial(PJSIP/''${EXTEN},25)
           same => n,Hangup()

          ; 911 — NO TRUNK. Say so audibly rather than fail silently.
          exten => 911,1,Answer()
           same => n,Playback(ss-noservice)
           same => n,Hangup()

          [switchboard]
          exten => s,1,Answer()
           ; 1.5 s, not 0.5: media takes a beat to flow after the 200 OK and the
           ; first call from a tailnet phone lost the start of the greeting.
           same => n,Wait(1.5)
           same => n,AGI(agi://127.0.0.1:${toString config.services.switchboard.agiPort})
           same => n,Hangup()

          ; Voice audition. The sample is Read()'s PROMPT, so a key pressed while
          ; it is still talking takes effect at once (Playback() would discard it
          ; — first attempt 2026-09-11: every press was ignored). After the
          ; sample, 15 s more of listening. Digit = next (wraps), * = again,
          ; # or silence = bye.
          [voices]
          exten => s,1,Answer()
           same => n,Wait(1.5)
           same => n,Set(N=1)
           same => n,Set(COUNT=${toString config.services.switchboard.auditionCount})
           same => n(play),Read(D,${config.services.switchboard.auditionDir}/sample''${N},1,,1,15)
           same => n,GotoIf($["''${D}" = ""]?bye)
           same => n,GotoIf($["''${D}" = "*"]?play)
           same => n,Set(N=$[''${N} % ''${COUNT} + 1])
           same => n,Goto(play)
           same => n(bye),Playback(vm-goodbye)
           same => n,Hangup()

          ; Outbound announcements arrive here from call files
          ; (switchboard outbound.py sets MESSAGE to a prompt path, no extension).
          ; The message plays twice: the first second after a pickup is always lost.
          [switchboard-announce]
          exten => s,1,Wait(1)
           same => n,Playback(''${MESSAGE})
           same => n,Wait(0.7)
           same => n,Playback(''${MESSAGE})
           same => n,Hangup()
        '';

        "rtp.conf" = ''
          [general]
          rtpstart=${toString cfg.rtpRange.from}
          rtpend=${toString cfg.rtpRange.to}
        '';
      };
    };

    # A dialplan/pjsip change should take effect on deploy. The upstream module
    # sets restartIfChanged = false (a restart drops live calls); a reload is
    # `core reload` — re-reads the confs, keeps calls and registrations.
    systemd.services.asterisk.reloadIfChanged = true;
    # ...but the confs are /etc files, not part of the unit, so name them as
    # reload triggers or a dialplan-only change deploys and does nothing
    # (2026-09-11: it reloaded once — when THIS flag appeared — then never).
    systemd.services.asterisk.reloadTriggers =
      map (f: config.environment.etc."asterisk/${f}".source) [ "pjsip.conf" "extensions.conf" "rtp.conf" ];

    # mkAfter: the upstream module's preStart creates /var/lib/asterisk from the
    # package skeleton only if it does NOT exist — this must run after it, or a
    # first boot would find the file's directory pre-created and skip the skeleton.
    # "+" = run as root regardless of the unit's user.
    systemd.services.asterisk.serviceConfig.ExecStartPre = lib.mkAfter [
      "+${genAuth} ${lib.concatStringsSep " " (lib.attrNames cfg.extensions)}"
    ];

    networking.firewall.interfaces = lib.genAttrs [ "enp3s0" "enp6s0u1" "tailscale0" ] (_: {
      allowedUDPPorts = [ 5060 ];
      allowedUDPPortRanges = [ cfg.rtpRange ];
    });
  };
}
