"""initial schema

Revision ID: f9c7931f6ef4
Revises: 
Create Date: 2026-08-12 11:17:24.884016
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'f9c7931f6ef4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # pg_trgm must exist before any of the GIN trigram indexes below can be
    # built. Creating it here rather than out of band keeps a fresh database
    # reproducible from migrations alone.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('sort_name', sa.String(length=400), nullable=False),
    sa.Column('ol_author_key', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ol_author_key')
    )
    op.create_index(op.f('ix_authors_sort_name'), 'authors', ['sort_name'], unique=False)
    op.create_index('ix_authors_sort_name_trgm', 'authors', ['sort_name'], unique=False, postgresql_using='gin', postgresql_ops={'sort_name': 'gin_trgm_ops'})
    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('hardcover_id', sa.String(length=64), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('household', 'room', 'shelf', 'section', 'box', name='location_kind'), nullable=False),
    sa.Column('sentinel_barcode', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sentinel_barcode')
    )
    op.create_index(op.f('ix_locations_household_id'), 'locations', ['household_id'], unique=False)
    op.create_index(op.f('ix_locations_parent_id'), 'locations', ['parent_id'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=600), nullable=False),
    sa.Column('sort_title', sa.String(length=600), nullable=False),
    sa.Column('subtitle', sa.String(length=600), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_author_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('series_position', sa.Float(), nullable=True),
    sa.Column('ol_work_keys', postgresql.ARRAY(sa.String(length=32)), server_default='{}', nullable=False),
    sa.Column('desired_copies', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('desired_copies >= 0', name='ck_works_desired_copies_nonneg'),
    sa.ForeignKeyConstraint(['primary_author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_works_ol_work_keys', 'works', ['ol_work_keys'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_works_sort_title'), 'works', ['sort_title'], unique=False)
    op.create_index('ix_works_sort_title_trgm', 'works', ['sort_title'], unique=False, postgresql_using='gin', postgresql_ops={'sort_title': 'gin_trgm_ops'})
    op.create_table('editions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('isbn13', sa.String(length=13), nullable=True),
    sa.Column('isbn10', sa.String(length=10), nullable=True),
    sa.Column('publisher', sa.String(length=300), nullable=True),
    sa.Column('publish_date', sa.String(length=64), nullable=True),
    sa.Column('publish_year', sa.Integer(), nullable=True),
    sa.Column('binding', sa.String(length=64), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('ol_edition_key', sa.String(length=32), nullable=True),
    sa.Column('cover_url', sa.String(length=600), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn13', name='uq_editions_isbn13'),
    sa.UniqueConstraint('ol_edition_key')
    )
    op.create_index(op.f('ix_editions_isbn10'), 'editions', ['isbn10'], unique=False)
    op.create_index(op.f('ix_editions_isbn13'), 'editions', ['isbn13'], unique=False)
    op.create_index(op.f('ix_editions_work_id'), 'editions', ['work_id'], unique=False)
    op.create_index('ix_editions_work_isbn13', 'editions', ['work_id', 'isbn13'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'fulfilled', 'cancelled', name='request_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_work_id'), 'requests', ['work_id'], unique=False)
    op.create_table('scan_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scanned_code', sa.String(length=64), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('matched_work_id', sa.Integer(), nullable=True),
    sa.Column('match_tier', sa.Enum('exact_isbn', 'work_expansion', 'fuzzy_title', 'manual', name='match_tier'), nullable=True),
    sa.Column('verdict', sa.String(length=32), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['matched_work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_events_scanned_code'), 'scan_events', ['scanned_code'], unique=False)
    op.create_table('want_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('work', 'author', 'publisher', 'series', 'topic', name='want_kind'), nullable=False),
    sa.Column('source', sa.Enum('sale_doc', 'flood_loss', 'series_gap', 'manual', name='want_source'), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('match_key', sa.String(length=300), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_want_rules_match_key'), 'want_rules', ['match_key'], unique=False)
    op.create_index('ix_want_rules_match_key_trgm', 'want_rules', ['match_key'], unique=False, postgresql_using='gin', postgresql_ops={'match_key': 'gin_trgm_ops'})
    op.create_table('copies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('owner_household_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('unverified', 'present', 'lost_flood', 'loaned', 'missing', 'discarded', name='copy_status'), nullable=False),
    sa.Column('provenance', sa.Enum('libib_import', 'flood_doc', 're_acquired', 'new_purchase', 'gift', 'manual', name='provenance'), nullable=False),
    sa.Column('source_collections', postgresql.ARRAY(sa.String(length=120)), server_default='{}', nullable=False),
    sa.Column('condition', sa.String(length=64), nullable=True),
    sa.Column('acquired_date', sa.Date(), nullable=True),
    sa.Column('label_barcode', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['owner_household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_barcode')
    )
    op.create_index(op.f('ix_copies_edition_id'), 'copies', ['edition_id'], unique=False)
    op.create_index(op.f('ix_copies_location_id'), 'copies', ['location_id'], unique=False)
    op.create_index(op.f('ix_copies_owner_household_id'), 'copies', ['owner_household_id'], unique=False)
    op.create_index(op.f('ix_copies_work_id'), 'copies', ['work_id'], unique=False)
    op.create_index('ix_copies_work_status', 'copies', ['work_id', 'status'], unique=False)
    op.create_table('want_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('have', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('match_key', sa.String(length=300), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['want_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_want_entries_match_key'), 'want_entries', ['match_key'], unique=False)
    op.create_index(op.f('ix_want_entries_rule_id'), 'want_entries', ['rule_id'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('copy_id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('loaned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['borrower_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['copy_id'], ['copies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_copy_id'), 'loans', ['copy_id'], unique=False)
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('series_gap', 'author_gap', 'flood_loss', 'manual', name='wishlist_reason'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('satisfied_by_copy_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['satisfied_by_copy_id'], ['copies.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id', 'reason', name='uq_wishlist_work_reason')
    )
    op.create_index(op.f('ix_wishlist_work_id'), 'wishlist', ['work_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishlist_work_id'), table_name='wishlist')
    op.drop_table('wishlist')
    op.drop_index(op.f('ix_loans_copy_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_want_entries_rule_id'), table_name='want_entries')
    op.drop_index(op.f('ix_want_entries_match_key'), table_name='want_entries')
    op.drop_table('want_entries')
    op.drop_index('ix_copies_work_status', table_name='copies')
    op.drop_index(op.f('ix_copies_work_id'), table_name='copies')
    op.drop_index(op.f('ix_copies_owner_household_id'), table_name='copies')
    op.drop_index(op.f('ix_copies_location_id'), table_name='copies')
    op.drop_index(op.f('ix_copies_edition_id'), table_name='copies')
    op.drop_table('copies')
    op.drop_index('ix_want_rules_match_key_trgm', table_name='want_rules', postgresql_using='gin', postgresql_ops={'match_key': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_want_rules_match_key'), table_name='want_rules')
    op.drop_table('want_rules')
    op.drop_index(op.f('ix_scan_events_scanned_code'), table_name='scan_events')
    op.drop_table('scan_events')
    op.drop_index(op.f('ix_requests_work_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index('ix_editions_work_isbn13', table_name='editions')
    op.drop_index(op.f('ix_editions_work_id'), table_name='editions')
    op.drop_index(op.f('ix_editions_isbn13'), table_name='editions')
    op.drop_index(op.f('ix_editions_isbn10'), table_name='editions')
    op.drop_table('editions')
    op.drop_index('ix_works_sort_title_trgm', table_name='works', postgresql_using='gin', postgresql_ops={'sort_title': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_works_sort_title'), table_name='works')
    op.drop_index('ix_works_ol_work_keys', table_name='works', postgresql_using='gin')
    op.drop_table('works')
    op.drop_table('people')
    op.drop_index(op.f('ix_locations_parent_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_household_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_table('series')
    op.drop_table('households')
    op.drop_index('ix_authors_sort_name_trgm', table_name='authors', postgresql_using='gin', postgresql_ops={'sort_name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_authors_sort_name'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###

    # Dropping the tables does not drop the ENUM TYPES they used — Postgres
    # keeps them, and the next upgrade-from-base then dies on
    # DuplicateObject: type "location_kind" already exists. Verified in the
    # 2026-08 audit: downgrade -> upgrade was never replayable. (An untested
    # downgrade is not a downgrade — 76d131433779 got this right for its own
    # enum; the initial schema did not.)
    for enum_name in ("location_kind", "copy_status", "provenance", "match_tier",
                      "request_status", "want_kind", "want_source",
                      "wishlist_reason"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
