"""edition cover_id

Revision ID: 2d6f3503ca23
Revises: f9c7931f6ef4
Create Date: 2026-08-12 14:26:18.665927
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '2d6f3503ca23'
down_revision = 'f9c7931f6ef4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('editions', sa.Column('cover_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_editions_cover_id'), 'editions', ['cover_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_editions_cover_id'), table_name='editions')
    op.drop_column('editions', 'cover_id')
    # ### end Alembic commands ###
