"""scan diagnostics

Revision ID: 5c61dbdfda47
Revises: 2f8c4b902675
Create Date: 2026-08-12 18:42:07.888877
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '5c61dbdfda47'
down_revision = '2f8c4b902675'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('page', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_events_at'), 'client_events', ['at'], unique=False)
    op.create_index(op.f('ix_client_events_kind'), 'client_events', ['kind'], unique=False)
    op.add_column('scan_events', sa.Column('source', sa.String(length=16), nullable=True))
    op.add_column('scan_events', sa.Column('client_verdict', sa.String(length=32), nullable=True))
    op.add_column('scan_events', sa.Column('user_agent', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_events', 'user_agent')
    op.drop_column('scan_events', 'client_verdict')
    op.drop_column('scan_events', 'source')
    op.drop_index(op.f('ix_client_events_kind'), table_name='client_events')
    op.drop_index(op.f('ix_client_events_at'), table_name='client_events')
    op.drop_table('client_events')
    # ### end Alembic commands ###
