"""work cover_edition_id

Revision ID: 9b5ce213ef87
Revises: 2d6f3503ca23
Create Date: 2026-08-12 14:51:52.167837
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '9b5ce213ef87'
down_revision = '2d6f3503ca23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('cover_edition_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'cover_edition_id')
    # ### end Alembic commands ###
