"""The human-editable source list.

Chris's framing: this is an RSS reader built backwards, and he wants to see the
sources and change them himself. The catalogue in git seeds the thing; it is
not where a person should have to go to drop a feed they are tired of.

So the surface is a SilverBullet page — `Areas/Newsdesk/Sources.md` — because
that space is already the source of truth for everything else the agent hands
him, and it edits fine from a phone.

The page has two halves with very different jobs:

  * a CONTROL BLOCK he writes into, one instruction per line;
  * a table this code regenerates from the database every run.

Editing the table does nothing. That is deliberate. Round-tripping a markdown
table is exactly the kind of parsing that works until the day he reflows a
column and silently loses a source. Instructions are unambiguous, auditable,
and survive being reformatted.

The database stays authoritative. The control block is applied at the START of
a run, before anything is collected, so an edit takes effect the same morning.
Applying it clears the block and writes what happened into "Last run" — a line
that failed is left in place with the reason appended, never silently dropped.
"""
from __future__ import annotations

import re
import sqlite3
from datetime import datetime, timezone

from . import feeds
from .db import now, write_atomic

CONTROL_RE = re.compile(r"```control\n(.*?)```", re.S)
# Values may be quoted, because source names have spaces in them —
# `name="Bitcoin Optech Newsletter"`. Without this, `name=Some Thing` silently
# captured only "Some" and left "Thing" glued to the URL.
SETTING_RE = re.compile(r'(\w+)=("[^"]*"|\S+)')

EDITABLE = {"lane", "tier", "cap", "weight", "name"}
TIERS = {"core", "watch", "firehose"}

PAGE_HEADER = """# Newsdesk sources

> The table below is regenerated by the newsdesk on every run — editing it does
> nothing. To change anything, write instructions in the control block and they
> are applied on the next run (the weekday brief, or the next poll).

## Add or change sources

```control
```

Instructions, one per line:

| | |
|---|---|
| `+ <url> lane=<lane> [tier=core] [cap=2] [name="Some Name"]` | add a feed. It is fetched and parsed first; if it is not a feed, the line comes back with the reason. Quote any value containing a space. |
| `- <name>` | stop using a source. It is disabled, never deleted, so its history and your grades survive. |
| `+ <name>` | turn a disabled source back on. |
| `= <name> cap=3 lane=ideas` | change `lane`, `tier`, `cap` or `weight`. |
| `? <url>` | just tell me what this is. Probes and reports; adds nothing. |

Lanes: `bitcoin` `release-radar` `macro` `energy` `agrarian` `linux` `network` `ideas`.
Tiers: `core` (low volume, read nearly everything) · `watch` (moderate) ·
`firehose` (high volume, hard cap, discovery only).
`cap` is the most items this source may put on one shortlist — it is what stops
a 200-a-week aggregator burying a 2-a-week newsletter.
"""


def _parse_line(line: str) -> dict | None:
    line = line.strip()
    if not line or line.startswith("#"):
        return None
    op, rest = line[0], line[1:].strip()
    if op not in "+-=?" or not rest:
        return {"op": "?bad", "raw": line, "error": "line must start with + - = or ?"}
    settings = {k: v.strip('"') for k, v in SETTING_RE.findall(rest)}
    target = SETTING_RE.sub("", rest).strip()
    bad = set(settings) - EDITABLE
    if bad:
        return {"op": "?bad", "raw": line,
                "error": f"unknown setting(s): {', '.join(sorted(bad))}"}
    return {"op": op, "target": target, "settings": settings, "raw": line}


def _validate_feed(url: str) -> tuple[bool, str]:
    try:
        res = feeds.fetch_feed(url)
    except Exception as e:  # noqa: BLE001
        return False, f"{type(e).__name__}: {e}"[:160]
    if not res.entries:
        return False, "parsed, but the feed contains no items"
    dates = sorted([e.published for e in res.entries if e.published])
    when = dates[-1].strftime("%Y-%m-%d") if dates else "unknown"
    return True, f"{len(res.entries)} items, newest {when}"


def apply_control(con: sqlite3.Connection, page_text: str) -> tuple[str, list[str]]:
    """Run the instructions in the control block. Returns (results, leftovers)."""
    m = CONTROL_RE.search(page_text or "")
    if not m:
        return "", []
    results: list[str] = []
    leftovers: list[str] = []

    for raw in m.group(1).splitlines():
        parsed = _parse_line(raw)
        if parsed is None:
            continue
        op = parsed["op"]

        if op == "?bad":
            leftovers.append(f"{parsed['raw']}   # {parsed['error']}")
            continue

        target, settings = parsed["target"], parsed["settings"]

        if op == "?":
            ok, detail = _validate_feed(target)
            results.append(f"**probe** `{target}` — "
                           + ("looks like a feed: " + detail if ok else "not usable: " + detail))
            continue

        if op == "-":
            row = con.execute("SELECT name FROM sources WHERE name = ?", (target,)).fetchone()
            if row is None:
                leftovers.append(f"{parsed['raw']}   # no source called '{target}'")
                continue
            con.execute("UPDATE sources SET enabled=0 WHERE name=?", (target,))
            results.append(f"**off** {target} — disabled. History and grades kept.")
            continue

        if op == "=":
            row = con.execute("SELECT name FROM sources WHERE name = ?", (target,)).fetchone()
            if row is None:
                leftovers.append(f"{parsed['raw']}   # no source called '{target}'")
                continue
            if not settings:
                leftovers.append(f"{parsed['raw']}   # nothing to change")
                continue
            err = _apply_settings(con, target, settings)
            if err:
                leftovers.append(f"{parsed['raw']}   # {err}")
            else:
                results.append(f"**changed** {target} — "
                               + ", ".join(f"{k}={v}" for k, v in sorted(settings.items())))
            continue

        # op == "+": re-enable by name, or add by URL
        if not target.startswith(("http://", "https://")):
            row = con.execute("SELECT name, enabled FROM sources WHERE name = ?",
                              (target,)).fetchone()
            if row is None:
                leftovers.append(f"{parsed['raw']}   # no source called '{target}'"
                                 " (to add a new one, give the feed URL)")
                continue
            con.execute("UPDATE sources SET enabled=1, fail_streak=0 WHERE name=?", (target,))
            results.append(f"**on** {target} — re-enabled.")
            continue

        # Only the first token is the URL; anything after it is stray text.
        url = target.split()[0]
        lane = settings.get("lane")
        if not lane:
            leftovers.append(f"{parsed['raw']}   # needs lane=<lane>")
            continue
        name = settings.get("name") or _name_from_url(url)
        if con.execute("SELECT 1 FROM sources WHERE name=? OR url=?", (name, url)).fetchone():
            leftovers.append(f"{parsed['raw']}   # already in the list as '{name}'")
            continue
        tier = settings.get("tier", "watch")
        if tier not in TIERS:
            leftovers.append(f"{parsed['raw']}   # tier must be one of {', '.join(sorted(TIERS))}")
            continue
        ok, detail = _validate_feed(url)
        if not ok:
            leftovers.append(f"{parsed['raw']}   # not added — {detail}")
            continue
        try:
            cap = int(settings.get("cap", 2))
        except ValueError:
            leftovers.append(f"{parsed['raw']}   # cap must be a number")
            continue
        con.execute(
            "INSERT INTO sources (name, lane, url, tier, cap, note) VALUES (?,?,?,?,?,?)",
            (name, lane, url, tier, cap, "Added by hand from the Sources page."))
        results.append(f"**added** {name} → `{lane}` / {tier}, cap {cap} — {detail}")

    con.commit()
    return "\n".join(f"- {r}" for r in results), leftovers


def _apply_settings(con: sqlite3.Connection, name: str, settings: dict) -> str | None:
    for key, value in settings.items():
        if key == "name":
            if con.execute("SELECT 1 FROM sources WHERE name=?", (value,)).fetchone():
                return f"a source called '{value}' already exists"
            con.execute("UPDATE sources SET name=? WHERE name=?", (value, name))
            name = value
        elif key == "tier":
            if value not in TIERS:
                return f"tier must be one of {', '.join(sorted(TIERS))}"
            con.execute("UPDATE sources SET tier=? WHERE name=?", (value, name))
        elif key in ("cap", "weight"):
            try:
                num = int(value) if key == "cap" else float(value)
            except ValueError:
                return f"{key} must be a number"
            con.execute(f"UPDATE sources SET {key}=? WHERE name=?", (num, name))
        elif key == "lane":
            con.execute("UPDATE sources SET lane=? WHERE name=?", (value, name))
            con.execute("UPDATE items SET lane=? WHERE source=?", (value, name))
    return None


def _name_from_url(url: str) -> str:
    host = re.sub(r"^https?://(www\.)?", "", url).split("/")[0]
    return host


def _status(row: sqlite3.Row) -> str:
    if not row["enabled"]:
        return "off"
    if row["dormant"]:
        return "dormant"
    if row["fail_streak"] >= 3:
        return f"failing ({row['fail_streak']})"
    return "ok"


def render_page(con: sqlite3.Connection) -> str:
    """The whole page: header, empty control block, then the live table."""
    rows = con.execute(
        "SELECT * FROM sources ORDER BY lane, name").fetchall()
    grades = dict(con.execute(
        "SELECT i.source, SUM(CASE WHEN g.value > 0 THEN 1 ELSE -1 END)"
        " FROM grades g JOIN items i ON i.id = g.item_id GROUP BY i.source").fetchall())

    out = [PAGE_HEADER, "", f"## Current sources ({len(rows)})", ""]
    lane = None
    for r in rows:
        if r["lane"] != lane:
            lane = r["lane"]
            out += ["", f"### {lane}", "",
                    "| Source | Tier | Cap | Status | Last item | Grades |",
                    "|---|---|---|---|---:|---:|"]
        last = (r["last_item_at"] or "")[:10] or "—"
        g = grades.get(r["name"])
        gtxt = ("—" if not g else (f"+{g}" if g > 0 else str(g)))
        out.append(f"| [{r['name']}]({r['url']}) | {r['tier']} | {r['cap']} "
                   f"| {_status(r)} | {last} | {gtxt} |")

    out += ["", "---", "",
            f"*Regenerated {datetime.now(timezone.utc).astimezone().strftime('%Y-%m-%d %H:%M %Z')}. "
            "The packaged catalogue in `ww4/flakes` seeds this list; anything you "
            "change here wins and survives a deploy.*"]
    return "\n".join(out) + "\n"


def sync(con: sqlite3.Connection, page_path) -> dict:
    """Apply whatever is in the control block, then rewrite the page."""
    existing = ""
    if page_path.exists():
        existing = page_path.read_text(errors="replace")

    results, leftovers = apply_control(con, existing)

    page = render_page(con)
    if leftovers:
        # Anything that failed goes back into the block with its reason, so it
        # is never quietly discarded.
        page = page.replace("```control\n```",
                            "```control\n" + "\n".join(leftovers) + "\n```")
    if results or leftovers:
        stamp = now()[:16].replace("T", " ")
        block = [f"## Last run ({stamp} UTC)", ""]
        block.append(results if results else "- nothing applied")
        if leftovers:
            block += ["", f"⚠️ {len(leftovers)} line(s) came back — see the "
                          "control block above for why."]
        page = page.replace("## Current sources", "\n".join(block) + "\n\n## Current sources", 1)

    write_atomic(page_path, page)
    return {"applied": results.count("\n- ") + (1 if results else 0),
            "returned": len(leftovers)}
